/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign application.  We provide SDKs for customers. They are generated using OpenAPI codegen, we encourage customers to use them as we also provide samples for them.  You can choose to build your own implementation manually or can use any compatible OpenAPI 3.0 generator like Swagger Codegen, OpenAPI codegen or any commercial generators.  If you need helping understanding how to use this API, don\'t waste too much time looking for it. Contact support-api@ezmax.ca, we\'re here to help. We are developpers so we know programmers don\'t like bad documentation. If you don\'t find what you need in the documentation, let us know, we\'ll improve it and put you rapidly up on track.
 *
 * The version of the OpenAPI document: 1.0.25
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApikeyRequest,
    ApikeyRequestFromJSON,
    ApikeyRequestFromJSONTyped,
    ApikeyRequestToJSON,
    MultilingualApikeyDescription,
    MultilingualApikeyDescriptionFromJSON,
    MultilingualApikeyDescriptionFromJSONTyped,
    MultilingualApikeyDescriptionToJSON,
} from './';

/**
 * An Apikey Object and children to create a complete structure
 * @export
 * @interface ApikeyRequestCompound
 */
export interface ApikeyRequestCompound {
    /**
     * The unique ID of the User
     * @type {number}
     * @memberof ApikeyRequestCompound
     */
    fkiUserID: number;
    /**
     * 
     * @type {MultilingualApikeyDescription}
     * @memberof ApikeyRequestCompound
     */
    objApikeyDescription: MultilingualApikeyDescription;
}

export function ApikeyRequestCompoundFromJSON(json: any): ApikeyRequestCompound {
    return ApikeyRequestCompoundFromJSONTyped(json, false);
}

export function ApikeyRequestCompoundFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApikeyRequestCompound {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fkiUserID': json['fkiUserID'],
        'objApikeyDescription': MultilingualApikeyDescriptionFromJSON(json['objApikeyDescription']),
    };
}

export function ApikeyRequestCompoundToJSON(value?: ApikeyRequestCompound | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fkiUserID': value.fkiUserID,
        'objApikeyDescription': MultilingualApikeyDescriptionToJSON(value.objApikeyDescription),
    };
}


