/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.43
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApikeyRequest,
    ApikeyRequestFromJSON,
    ApikeyRequestFromJSONTyped,
    ApikeyRequestToJSON,
    ApikeyRequestCompound,
    ApikeyRequestCompoundFromJSON,
    ApikeyRequestCompoundFromJSONTyped,
    ApikeyRequestCompoundToJSON,
} from './';

/**
 * Request for the /1/object/apikey/createObject API Request
 * @export
 * @interface ApikeyCreateObjectV1Request
 */
export interface ApikeyCreateObjectV1Request {
    /**
     * 
     * @type {ApikeyRequest}
     * @memberof ApikeyCreateObjectV1Request
     */
    objApikey?: ApikeyRequest;
    /**
     * 
     * @type {ApikeyRequestCompound}
     * @memberof ApikeyCreateObjectV1Request
     */
    objApikeyCompound?: ApikeyRequestCompound;
}

export function ApikeyCreateObjectV1RequestFromJSON(json: any): ApikeyCreateObjectV1Request {
    return ApikeyCreateObjectV1RequestFromJSONTyped(json, false);
}

export function ApikeyCreateObjectV1RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApikeyCreateObjectV1Request {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'objApikey': !exists(json, 'objApikey') ? undefined : ApikeyRequestFromJSON(json['objApikey']),
        'objApikeyCompound': !exists(json, 'objApikeyCompound') ? undefined : ApikeyRequestCompoundFromJSON(json['objApikeyCompound']),
    };
}

export function ApikeyCreateObjectV1RequestToJSON(value?: ApikeyCreateObjectV1Request | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'objApikey': ApikeyRequestToJSON(value.objApikey),
        'objApikeyCompound': ApikeyRequestCompoundToJSON(value.objApikeyCompound),
    };
}


