/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.47
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AuthenticateAuthenticateV2ResponseMPayload,
    AuthenticateAuthenticateV2ResponseMPayloadFromJSON,
    AuthenticateAuthenticateV2ResponseMPayloadFromJSONTyped,
    AuthenticateAuthenticateV2ResponseMPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface AuthenticateAuthenticateV2ResponseAllOf
 */
export interface AuthenticateAuthenticateV2ResponseAllOf {
    /**
     * 
     * @type {AuthenticateAuthenticateV2ResponseMPayload}
     * @memberof AuthenticateAuthenticateV2ResponseAllOf
     */
    mPayload: AuthenticateAuthenticateV2ResponseMPayload;
}

export function AuthenticateAuthenticateV2ResponseAllOfFromJSON(json: any): AuthenticateAuthenticateV2ResponseAllOf {
    return AuthenticateAuthenticateV2ResponseAllOfFromJSONTyped(json, false);
}

export function AuthenticateAuthenticateV2ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticateAuthenticateV2ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mPayload': AuthenticateAuthenticateV2ResponseMPayloadFromJSON(json['mPayload']),
    };
}

export function AuthenticateAuthenticateV2ResponseAllOfToJSON(value?: AuthenticateAuthenticateV2ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mPayload': AuthenticateAuthenticateV2ResponseMPayloadToJSON(value.mPayload),
    };
}

