/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CommonGetAutocompleteV1ResponseMPayload,
    CommonGetAutocompleteV1ResponseMPayloadFromJSON,
    CommonGetAutocompleteV1ResponseMPayloadFromJSONTyped,
    CommonGetAutocompleteV1ResponseMPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface CommonGetAutocompleteV1ResponseAllOf
 */
export interface CommonGetAutocompleteV1ResponseAllOf {
    /**
     * 
     * @type {Array<CommonGetAutocompleteV1ResponseMPayload>}
     * @memberof CommonGetAutocompleteV1ResponseAllOf
     */
    mPayload: Array<CommonGetAutocompleteV1ResponseMPayload>;
}

export function CommonGetAutocompleteV1ResponseAllOfFromJSON(json: any): CommonGetAutocompleteV1ResponseAllOf {
    return CommonGetAutocompleteV1ResponseAllOfFromJSONTyped(json, false);
}

export function CommonGetAutocompleteV1ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonGetAutocompleteV1ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mPayload': ((json['mPayload'] as Array<any>).map(CommonGetAutocompleteV1ResponseMPayloadFromJSON)),
    };
}

export function CommonGetAutocompleteV1ResponseAllOfToJSON(value?: CommonGetAutocompleteV1ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mPayload': ((value.mPayload as Array<any>).map(CommonGetAutocompleteV1ResponseMPayloadToJSON)),
    };
}

