/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.44
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Definition of objSQLQuery Object
 * @export
 * @interface CommonResponseObjSQLQuery
 */
export interface CommonResponseObjSQLQuery {
    /**
     * The SQL Query
     * @type {string}
     * @memberof CommonResponseObjSQLQuery
     */
    sQuery: string;
    /**
     * Execution time of the SQL Query in seconds
     * @type {number}
     * @memberof CommonResponseObjSQLQuery
     */
    fDuration: number;
}

export function CommonResponseObjSQLQueryFromJSON(json: any): CommonResponseObjSQLQuery {
    return CommonResponseObjSQLQueryFromJSONTyped(json, false);
}

export function CommonResponseObjSQLQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseObjSQLQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sQuery': json['sQuery'],
        'fDuration': json['fDuration'],
    };
}

export function CommonResponseObjSQLQueryToJSON(value?: CommonResponseObjSQLQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sQuery': value.sQuery,
        'fDuration': value.fDuration,
    };
}


