/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign application.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EzsignfoldersignerassociationRequest,
    EzsignfoldersignerassociationRequestFromJSON,
    EzsignfoldersignerassociationRequestFromJSONTyped,
    EzsignfoldersignerassociationRequestToJSON,
} from './';

/**
 * Request for the /1/object/ezsignfoldersignerassociation/editObject API Request
 * @export
 * @interface EzsignfoldersignerassociationEditObjectV1Request
 */
export interface EzsignfoldersignerassociationEditObjectV1Request {
    /**
     * 
     * @type {EzsignfoldersignerassociationRequest}
     * @memberof EzsignfoldersignerassociationEditObjectV1Request
     */
    objEzsignfoldersignerassociation?: EzsignfoldersignerassociationRequest;
}

export function EzsignfoldersignerassociationEditObjectV1RequestFromJSON(json: any): EzsignfoldersignerassociationEditObjectV1Request {
    return EzsignfoldersignerassociationEditObjectV1RequestFromJSONTyped(json, false);
}

export function EzsignfoldersignerassociationEditObjectV1RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EzsignfoldersignerassociationEditObjectV1Request {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'objEzsignfoldersignerassociation': !exists(json, 'objEzsignfoldersignerassociation') ? undefined : EzsignfoldersignerassociationRequestFromJSON(json['objEzsignfoldersignerassociation']),
    };
}

export function EzsignfoldersignerassociationEditObjectV1RequestToJSON(value?: EzsignfoldersignerassociationEditObjectV1Request | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'objEzsignfoldersignerassociation': EzsignfoldersignerassociationRequestToJSON(value.objEzsignfoldersignerassociation),
    };
}


