/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.47
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EzsignfoldersignerassociationGetObjectV1ResponseAllOf
 */
export interface EzsignfoldersignerassociationGetObjectV1ResponseAllOf {
    /**
     * Payload for the /1/object/ezsignfoldersignerassociation/getObject API Request
     * @type {object}
     * @memberof EzsignfoldersignerassociationGetObjectV1ResponseAllOf
     */
    mPayload: object;
}

export function EzsignfoldersignerassociationGetObjectV1ResponseAllOfFromJSON(json: any): EzsignfoldersignerassociationGetObjectV1ResponseAllOf {
    return EzsignfoldersignerassociationGetObjectV1ResponseAllOfFromJSONTyped(json, false);
}

export function EzsignfoldersignerassociationGetObjectV1ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): EzsignfoldersignerassociationGetObjectV1ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mPayload': json['mPayload'],
    };
}

export function EzsignfoldersignerassociationGetObjectV1ResponseAllOfToJSON(value?: EzsignfoldersignerassociationGetObjectV1ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mPayload': value.mPayload,
    };
}

