/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EzsignsignerRequestCompound,
    EzsignsignerRequestCompoundFromJSON,
    EzsignsignerRequestCompoundFromJSONTyped,
    EzsignsignerRequestCompoundToJSON,
} from './';

/**
 * 
 * @export
 * @interface EzsignfoldersignerassociationRequestCompoundAllOf
 */
export interface EzsignfoldersignerassociationRequestCompoundAllOf {
    /**
     * 
     * @type {EzsignsignerRequestCompound}
     * @memberof EzsignfoldersignerassociationRequestCompoundAllOf
     */
    objEzsignsigner?: EzsignsignerRequestCompound;
}

export function EzsignfoldersignerassociationRequestCompoundAllOfFromJSON(json: any): EzsignfoldersignerassociationRequestCompoundAllOf {
    return EzsignfoldersignerassociationRequestCompoundAllOfFromJSONTyped(json, false);
}

export function EzsignfoldersignerassociationRequestCompoundAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): EzsignfoldersignerassociationRequestCompoundAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'objEzsignsigner': !exists(json, 'objEzsignsigner') ? undefined : EzsignsignerRequestCompoundFromJSON(json['objEzsignsigner']),
    };
}

export function EzsignfoldersignerassociationRequestCompoundAllOfToJSON(value?: EzsignfoldersignerassociationRequestCompoundAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'objEzsignsigner': EzsignsignerRequestCompoundToJSON(value.objEzsignsigner),
    };
}

