/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EzsigndocumentCreateObjectV1ResponseMPayload,
    EzsigndocumentCreateObjectV1ResponseMPayloadFromJSON,
    EzsigndocumentCreateObjectV1ResponseMPayloadFromJSONTyped,
    EzsigndocumentCreateObjectV1ResponseMPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface EzsigndocumentCreateObjectV1ResponseAllOf
 */
export interface EzsigndocumentCreateObjectV1ResponseAllOf {
    /**
     * 
     * @type {EzsigndocumentCreateObjectV1ResponseMPayload}
     * @memberof EzsigndocumentCreateObjectV1ResponseAllOf
     */
    mPayload: EzsigndocumentCreateObjectV1ResponseMPayload;
}

export function EzsigndocumentCreateObjectV1ResponseAllOfFromJSON(json: any): EzsigndocumentCreateObjectV1ResponseAllOf {
    return EzsigndocumentCreateObjectV1ResponseAllOfFromJSONTyped(json, false);
}

export function EzsigndocumentCreateObjectV1ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): EzsigndocumentCreateObjectV1ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mPayload': EzsigndocumentCreateObjectV1ResponseMPayloadFromJSON(json['mPayload']),
    };
}

export function EzsigndocumentCreateObjectV1ResponseAllOfToJSON(value?: EzsigndocumentCreateObjectV1ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mPayload': EzsigndocumentCreateObjectV1ResponseMPayloadToJSON(value.mPayload),
    };
}

