/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.47
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CommonResponse,
    CommonResponseFromJSON,
    CommonResponseFromJSONTyped,
    CommonResponseToJSON,
    CommonResponseObjDebug,
    CommonResponseObjDebugFromJSON,
    CommonResponseObjDebugFromJSONTyped,
    CommonResponseObjDebugToJSON,
    CommonResponseObjDebugPayload,
    CommonResponseObjDebugPayloadFromJSON,
    CommonResponseObjDebugPayloadFromJSONTyped,
    CommonResponseObjDebugPayloadToJSON,
    EzsigndocumentGetWordsPositionsV1ResponseAllOf,
    EzsigndocumentGetWordsPositionsV1ResponseAllOfFromJSON,
    EzsigndocumentGetWordsPositionsV1ResponseAllOfFromJSONTyped,
    EzsigndocumentGetWordsPositionsV1ResponseAllOfToJSON,
    EzsigndocumentGetWordsPositionsV1ResponseMPayload,
    EzsigndocumentGetWordsPositionsV1ResponseMPayloadFromJSON,
    EzsigndocumentGetWordsPositionsV1ResponseMPayloadFromJSONTyped,
    EzsigndocumentGetWordsPositionsV1ResponseMPayloadToJSON,
} from './';

/**
 * Response for the /1/object/ezsigndocument/{pkiEzsigndocumentID}/getWordsPositions API Request
 * @export
 * @interface EzsigndocumentGetWordsPositionsV1Response
 */
export interface EzsigndocumentGetWordsPositionsV1Response {
    /**
     * 
     * @type {EzsigndocumentGetWordsPositionsV1ResponseMPayload}
     * @memberof EzsigndocumentGetWordsPositionsV1Response
     */
    mPayload: EzsigndocumentGetWordsPositionsV1ResponseMPayload;
    /**
     * 
     * @type {CommonResponseObjDebugPayload}
     * @memberof EzsigndocumentGetWordsPositionsV1Response
     */
    objDebugPayload?: CommonResponseObjDebugPayload;
    /**
     * 
     * @type {CommonResponseObjDebug}
     * @memberof EzsigndocumentGetWordsPositionsV1Response
     */
    objDebug?: CommonResponseObjDebug;
}

export function EzsigndocumentGetWordsPositionsV1ResponseFromJSON(json: any): EzsigndocumentGetWordsPositionsV1Response {
    return EzsigndocumentGetWordsPositionsV1ResponseFromJSONTyped(json, false);
}

export function EzsigndocumentGetWordsPositionsV1ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EzsigndocumentGetWordsPositionsV1Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mPayload': EzsigndocumentGetWordsPositionsV1ResponseMPayloadFromJSON(json['mPayload']),
        'objDebugPayload': !exists(json, 'objDebugPayload') ? undefined : CommonResponseObjDebugPayloadFromJSON(json['objDebugPayload']),
        'objDebug': !exists(json, 'objDebug') ? undefined : CommonResponseObjDebugFromJSON(json['objDebug']),
    };
}

export function EzsigndocumentGetWordsPositionsV1ResponseToJSON(value?: EzsigndocumentGetWordsPositionsV1Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mPayload': EzsigndocumentGetWordsPositionsV1ResponseMPayloadToJSON(value.mPayload),
        'objDebugPayload': CommonResponseObjDebugPayloadToJSON(value.objDebugPayload),
        'objDebug': CommonResponseObjDebugToJSON(value.objDebug),
    };
}

