/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EzsigndocumentGetWordsPositionsV1ResponseMPayload,
    EzsigndocumentGetWordsPositionsV1ResponseMPayloadFromJSON,
    EzsigndocumentGetWordsPositionsV1ResponseMPayloadFromJSONTyped,
    EzsigndocumentGetWordsPositionsV1ResponseMPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface EzsigndocumentGetWordsPositionsV1ResponseAllOf
 */
export interface EzsigndocumentGetWordsPositionsV1ResponseAllOf {
    /**
     * 
     * @type {EzsigndocumentGetWordsPositionsV1ResponseMPayload}
     * @memberof EzsigndocumentGetWordsPositionsV1ResponseAllOf
     */
    mPayload: EzsigndocumentGetWordsPositionsV1ResponseMPayload;
}

export function EzsigndocumentGetWordsPositionsV1ResponseAllOfFromJSON(json: any): EzsigndocumentGetWordsPositionsV1ResponseAllOf {
    return EzsigndocumentGetWordsPositionsV1ResponseAllOfFromJSONTyped(json, false);
}

export function EzsigndocumentGetWordsPositionsV1ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): EzsigndocumentGetWordsPositionsV1ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mPayload': EzsigndocumentGetWordsPositionsV1ResponseMPayloadFromJSON(json['mPayload']),
    };
}

export function EzsigndocumentGetWordsPositionsV1ResponseAllOfToJSON(value?: EzsigndocumentGetWordsPositionsV1ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mPayload': EzsigndocumentGetWordsPositionsV1ResponseMPayloadToJSON(value.mPayload),
    };
}

