/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CommonResponse,
    CommonResponseFromJSON,
    CommonResponseFromJSONTyped,
    CommonResponseToJSON,
    CommonResponseObjDebug,
    CommonResponseObjDebugFromJSON,
    CommonResponseObjDebugFromJSONTyped,
    CommonResponseObjDebugToJSON,
    CommonResponseObjDebugPayload,
    CommonResponseObjDebugPayloadFromJSON,
    CommonResponseObjDebugPayloadFromJSONTyped,
    CommonResponseObjDebugPayloadToJSON,
    EzsigndocumentGetEzsignpagesV1ResponseAllOf,
    EzsigndocumentGetEzsignpagesV1ResponseAllOfFromJSON,
    EzsigndocumentGetEzsignpagesV1ResponseAllOfFromJSONTyped,
    EzsigndocumentGetEzsignpagesV1ResponseAllOfToJSON,
    EzsigndocumentGetEzsignpagesV1ResponseMPayload,
    EzsigndocumentGetEzsignpagesV1ResponseMPayloadFromJSON,
    EzsigndocumentGetEzsignpagesV1ResponseMPayloadFromJSONTyped,
    EzsigndocumentGetEzsignpagesV1ResponseMPayloadToJSON,
} from './';

/**
 * Response for the /1/object/ezsigndocument/{pkiEzsigndocument}/getEzsignpages API Request
 * @export
 * @interface EzsigndocumentGetEzsignpagesV1Response
 */
export interface EzsigndocumentGetEzsignpagesV1Response {
    /**
     * 
     * @type {EzsigndocumentGetEzsignpagesV1ResponseMPayload}
     * @memberof EzsigndocumentGetEzsignpagesV1Response
     */
    mPayload: EzsigndocumentGetEzsignpagesV1ResponseMPayload;
    /**
     * 
     * @type {CommonResponseObjDebugPayload}
     * @memberof EzsigndocumentGetEzsignpagesV1Response
     */
    objDebugPayload?: CommonResponseObjDebugPayload;
    /**
     * 
     * @type {CommonResponseObjDebug}
     * @memberof EzsigndocumentGetEzsignpagesV1Response
     */
    objDebug?: CommonResponseObjDebug;
}

export function EzsigndocumentGetEzsignpagesV1ResponseFromJSON(json: any): EzsigndocumentGetEzsignpagesV1Response {
    return EzsigndocumentGetEzsignpagesV1ResponseFromJSONTyped(json, false);
}

export function EzsigndocumentGetEzsignpagesV1ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EzsigndocumentGetEzsignpagesV1Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mPayload': EzsigndocumentGetEzsignpagesV1ResponseMPayloadFromJSON(json['mPayload']),
        'objDebugPayload': !exists(json, 'objDebugPayload') ? undefined : CommonResponseObjDebugPayloadFromJSON(json['objDebugPayload']),
        'objDebug': !exists(json, 'objDebug') ? undefined : CommonResponseObjDebugFromJSON(json['objDebug']),
    };
}

export function EzsigndocumentGetEzsignpagesV1ResponseToJSON(value?: EzsigndocumentGetEzsignpagesV1Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mPayload': EzsigndocumentGetEzsignpagesV1ResponseMPayloadToJSON(value.mPayload),
        'objDebugPayload': CommonResponseObjDebugPayloadToJSON(value.objDebugPayload),
        'objDebug': CommonResponseObjDebugToJSON(value.objDebug),
    };
}

