/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EzsigndocumentGetDownloadUrlV1ResponseMPayload,
    EzsigndocumentGetDownloadUrlV1ResponseMPayloadFromJSON,
    EzsigndocumentGetDownloadUrlV1ResponseMPayloadFromJSONTyped,
    EzsigndocumentGetDownloadUrlV1ResponseMPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface EzsigndocumentGetDownloadUrlV1ResponseAllOf
 */
export interface EzsigndocumentGetDownloadUrlV1ResponseAllOf {
    /**
     * 
     * @type {EzsigndocumentGetDownloadUrlV1ResponseMPayload}
     * @memberof EzsigndocumentGetDownloadUrlV1ResponseAllOf
     */
    mPayload: EzsigndocumentGetDownloadUrlV1ResponseMPayload;
}

export function EzsigndocumentGetDownloadUrlV1ResponseAllOfFromJSON(json: any): EzsigndocumentGetDownloadUrlV1ResponseAllOf {
    return EzsigndocumentGetDownloadUrlV1ResponseAllOfFromJSONTyped(json, false);
}

export function EzsigndocumentGetDownloadUrlV1ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): EzsigndocumentGetDownloadUrlV1ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mPayload': EzsigndocumentGetDownloadUrlV1ResponseMPayloadFromJSON(json['mPayload']),
    };
}

export function EzsigndocumentGetDownloadUrlV1ResponseAllOfToJSON(value?: EzsigndocumentGetDownloadUrlV1ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mPayload': EzsigndocumentGetDownloadUrlV1ResponseMPayloadToJSON(value.mPayload),
    };
}

