/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EzsigndocumentGetEzsignpagesV1ResponseMPayload,
    EzsigndocumentGetEzsignpagesV1ResponseMPayloadFromJSON,
    EzsigndocumentGetEzsignpagesV1ResponseMPayloadFromJSONTyped,
    EzsigndocumentGetEzsignpagesV1ResponseMPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface EzsigndocumentGetEzsignpagesV1ResponseAllOf
 */
export interface EzsigndocumentGetEzsignpagesV1ResponseAllOf {
    /**
     * 
     * @type {EzsigndocumentGetEzsignpagesV1ResponseMPayload}
     * @memberof EzsigndocumentGetEzsignpagesV1ResponseAllOf
     */
    mPayload: EzsigndocumentGetEzsignpagesV1ResponseMPayload;
}

export function EzsigndocumentGetEzsignpagesV1ResponseAllOfFromJSON(json: any): EzsigndocumentGetEzsignpagesV1ResponseAllOf {
    return EzsigndocumentGetEzsignpagesV1ResponseAllOfFromJSONTyped(json, false);
}

export function EzsigndocumentGetEzsignpagesV1ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): EzsigndocumentGetEzsignpagesV1ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mPayload': EzsigndocumentGetEzsignpagesV1ResponseMPayloadFromJSON(json['mPayload']),
    };
}

export function EzsigndocumentGetEzsignpagesV1ResponseAllOfToJSON(value?: EzsigndocumentGetEzsignpagesV1ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mPayload': EzsigndocumentGetEzsignpagesV1ResponseMPayloadToJSON(value.mPayload),
    };
}

