/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign application.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EzsigndocumentRequest,
    EzsigndocumentRequestFromJSON,
    EzsigndocumentRequestFromJSONTyped,
    EzsigndocumentRequestToJSON,
} from './';

/**
 * Request for the /1/object/ezsigndocument/editObject API Request
 * @export
 * @interface EzsigndocumentEditObjectV1Request
 */
export interface EzsigndocumentEditObjectV1Request {
    /**
     * 
     * @type {EzsigndocumentRequest}
     * @memberof EzsigndocumentEditObjectV1Request
     */
    objEzsigndocument?: EzsigndocumentRequest;
}

export function EzsigndocumentEditObjectV1RequestFromJSON(json: any): EzsigndocumentEditObjectV1Request {
    return EzsigndocumentEditObjectV1RequestFromJSONTyped(json, false);
}

export function EzsigndocumentEditObjectV1RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EzsigndocumentEditObjectV1Request {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'objEzsigndocument': !exists(json, 'objEzsigndocument') ? undefined : EzsigndocumentRequestFromJSON(json['objEzsigndocument']),
    };
}

export function EzsigndocumentEditObjectV1RequestToJSON(value?: EzsigndocumentEditObjectV1Request | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'objEzsigndocument': EzsigndocumentRequestToJSON(value.objEzsigndocument),
    };
}


