/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.47
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EzsignfolderGetObjectV1ResponseMPayload,
    EzsignfolderGetObjectV1ResponseMPayloadFromJSON,
    EzsignfolderGetObjectV1ResponseMPayloadFromJSONTyped,
    EzsignfolderGetObjectV1ResponseMPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface EzsignfolderGetObjectV1ResponseAllOf
 */
export interface EzsignfolderGetObjectV1ResponseAllOf {
    /**
     * 
     * @type {EzsignfolderGetObjectV1ResponseMPayload}
     * @memberof EzsignfolderGetObjectV1ResponseAllOf
     */
    mPayload: EzsignfolderGetObjectV1ResponseMPayload;
}

export function EzsignfolderGetObjectV1ResponseAllOfFromJSON(json: any): EzsignfolderGetObjectV1ResponseAllOf {
    return EzsignfolderGetObjectV1ResponseAllOfFromJSONTyped(json, false);
}

export function EzsignfolderGetObjectV1ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): EzsignfolderGetObjectV1ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mPayload': EzsignfolderGetObjectV1ResponseMPayloadFromJSON(json['mPayload']),
    };
}

export function EzsignfolderGetObjectV1ResponseAllOfToJSON(value?: EzsignfolderGetObjectV1ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mPayload': EzsignfolderGetObjectV1ResponseMPayloadToJSON(value.mPayload),
    };
}

