/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EzsigndocumentGetObjectV1ResponseMPayload,
    EzsigndocumentGetObjectV1ResponseMPayloadFromJSON,
    EzsigndocumentGetObjectV1ResponseMPayloadFromJSONTyped,
    EzsigndocumentGetObjectV1ResponseMPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface EzsigndocumentGetObjectV1ResponseAllOf
 */
export interface EzsigndocumentGetObjectV1ResponseAllOf {
    /**
     * 
     * @type {EzsigndocumentGetObjectV1ResponseMPayload}
     * @memberof EzsigndocumentGetObjectV1ResponseAllOf
     */
    mPayload: EzsigndocumentGetObjectV1ResponseMPayload;
}

export function EzsigndocumentGetObjectV1ResponseAllOfFromJSON(json: any): EzsigndocumentGetObjectV1ResponseAllOf {
    return EzsigndocumentGetObjectV1ResponseAllOfFromJSONTyped(json, false);
}

export function EzsigndocumentGetObjectV1ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): EzsigndocumentGetObjectV1ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mPayload': EzsigndocumentGetObjectV1ResponseMPayloadFromJSON(json['mPayload']),
    };
}

export function EzsigndocumentGetObjectV1ResponseAllOfToJSON(value?: EzsigndocumentGetObjectV1ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mPayload': EzsigndocumentGetObjectV1ResponseMPayloadToJSON(value.mPayload),
    };
}

