/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.37
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Payload for the /1/object/ezsignfoldersignerassociation/createObject API Request
 * @export
 * @interface EzsignfoldersignerassociationCreateObjectV1ResponseMPayload
 */
export interface EzsignfoldersignerassociationCreateObjectV1ResponseMPayload {
    /**
     * An array of unique IDs representing the object that were requested to be created.
     * 
     * They are returned in the same order as the array containing the objects to be created that was sent in the request.
     * @type {Array<number>}
     * @memberof EzsignfoldersignerassociationCreateObjectV1ResponseMPayload
     */
    a_pkiEzsignfoldersignerassociationID: Array<number>;
}

export function EzsignfoldersignerassociationCreateObjectV1ResponseMPayloadFromJSON(json: any): EzsignfoldersignerassociationCreateObjectV1ResponseMPayload {
    return EzsignfoldersignerassociationCreateObjectV1ResponseMPayloadFromJSONTyped(json, false);
}

export function EzsignfoldersignerassociationCreateObjectV1ResponseMPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): EzsignfoldersignerassociationCreateObjectV1ResponseMPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'a_pkiEzsignfoldersignerassociationID': json['a_pkiEzsignfoldersignerassociationID'],
    };
}

export function EzsignfoldersignerassociationCreateObjectV1ResponseMPayloadToJSON(value?: EzsignfoldersignerassociationCreateObjectV1ResponseMPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'a_pkiEzsignfoldersignerassociationID': value.a_pkiEzsignfoldersignerassociationID,
    };
}


