/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EzsignfoldersignerassociationCreateObjectV1ResponseMPayload,
    EzsignfoldersignerassociationCreateObjectV1ResponseMPayloadFromJSON,
    EzsignfoldersignerassociationCreateObjectV1ResponseMPayloadFromJSONTyped,
    EzsignfoldersignerassociationCreateObjectV1ResponseMPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface EzsignfoldersignerassociationCreateObjectV1ResponseAllOf
 */
export interface EzsignfoldersignerassociationCreateObjectV1ResponseAllOf {
    /**
     * 
     * @type {EzsignfoldersignerassociationCreateObjectV1ResponseMPayload}
     * @memberof EzsignfoldersignerassociationCreateObjectV1ResponseAllOf
     */
    mPayload: EzsignfoldersignerassociationCreateObjectV1ResponseMPayload;
}

export function EzsignfoldersignerassociationCreateObjectV1ResponseAllOfFromJSON(json: any): EzsignfoldersignerassociationCreateObjectV1ResponseAllOf {
    return EzsignfoldersignerassociationCreateObjectV1ResponseAllOfFromJSONTyped(json, false);
}

export function EzsignfoldersignerassociationCreateObjectV1ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): EzsignfoldersignerassociationCreateObjectV1ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mPayload': EzsignfoldersignerassociationCreateObjectV1ResponseMPayloadFromJSON(json['mPayload']),
    };
}

export function EzsignfoldersignerassociationCreateObjectV1ResponseAllOfToJSON(value?: EzsignfoldersignerassociationCreateObjectV1ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mPayload': EzsignfoldersignerassociationCreateObjectV1ResponseMPayloadToJSON(value.mPayload),
    };
}

