/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EzsignpageResponse,
    EzsignpageResponseFromJSON,
    EzsignpageResponseFromJSONTyped,
    EzsignpageResponseToJSON,
} from './';

/**
 * Payload for the /1/object/ezsigndocument/{pkiEzsigndocument}/getEzsignpages API Request
 * @export
 * @interface EzsigndocumentGetEzsignpagesV1ResponseMPayload
 */
export interface EzsigndocumentGetEzsignpagesV1ResponseMPayload {
    /**
     * 
     * @type {Array<EzsignpageResponse>}
     * @memberof EzsigndocumentGetEzsignpagesV1ResponseMPayload
     */
    a_objEzsignpage: Array<EzsignpageResponse>;
}

export function EzsigndocumentGetEzsignpagesV1ResponseMPayloadFromJSON(json: any): EzsigndocumentGetEzsignpagesV1ResponseMPayload {
    return EzsigndocumentGetEzsignpagesV1ResponseMPayloadFromJSONTyped(json, false);
}

export function EzsigndocumentGetEzsignpagesV1ResponseMPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): EzsigndocumentGetEzsignpagesV1ResponseMPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'a_objEzsignpage': ((json['a_objEzsignpage'] as Array<any>).map(EzsignpageResponseFromJSON)),
    };
}

export function EzsigndocumentGetEzsignpagesV1ResponseMPayloadToJSON(value?: EzsigndocumentGetEzsignpagesV1ResponseMPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'a_objEzsignpage': ((value.a_objEzsignpage as Array<any>).map(EzsignpageResponseToJSON)),
    };
}

