/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.47
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EzsignfoldersignerassociationGetInPersonLoginUrlV1ResponseMPayload,
    EzsignfoldersignerassociationGetInPersonLoginUrlV1ResponseMPayloadFromJSON,
    EzsignfoldersignerassociationGetInPersonLoginUrlV1ResponseMPayloadFromJSONTyped,
    EzsignfoldersignerassociationGetInPersonLoginUrlV1ResponseMPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface EzsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf
 */
export interface EzsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf {
    /**
     * 
     * @type {EzsignfoldersignerassociationGetInPersonLoginUrlV1ResponseMPayload}
     * @memberof EzsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf
     */
    mPayload: EzsignfoldersignerassociationGetInPersonLoginUrlV1ResponseMPayload;
}

export function EzsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOfFromJSON(json: any): EzsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf {
    return EzsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOfFromJSONTyped(json, false);
}

export function EzsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): EzsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mPayload': EzsignfoldersignerassociationGetInPersonLoginUrlV1ResponseMPayloadFromJSON(json['mPayload']),
    };
}

export function EzsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOfToJSON(value?: EzsignfoldersignerassociationGetInPersonLoginUrlV1ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mPayload': EzsignfoldersignerassociationGetInPersonLoginUrlV1ResponseMPayloadToJSON(value.mPayload),
    };
}

