/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EzsignsignatureCreateObjectV1ResponseMPayload,
    EzsignsignatureCreateObjectV1ResponseMPayloadFromJSON,
    EzsignsignatureCreateObjectV1ResponseMPayloadFromJSONTyped,
    EzsignsignatureCreateObjectV1ResponseMPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface EzsignsignatureCreateObjectV1ResponseAllOf
 */
export interface EzsignsignatureCreateObjectV1ResponseAllOf {
    /**
     * 
     * @type {EzsignsignatureCreateObjectV1ResponseMPayload}
     * @memberof EzsignsignatureCreateObjectV1ResponseAllOf
     */
    mPayload: EzsignsignatureCreateObjectV1ResponseMPayload;
}

export function EzsignsignatureCreateObjectV1ResponseAllOfFromJSON(json: any): EzsignsignatureCreateObjectV1ResponseAllOf {
    return EzsignsignatureCreateObjectV1ResponseAllOfFromJSONTyped(json, false);
}

export function EzsignsignatureCreateObjectV1ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): EzsignsignatureCreateObjectV1ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mPayload': EzsignsignatureCreateObjectV1ResponseMPayloadFromJSON(json['mPayload']),
    };
}

export function EzsignsignatureCreateObjectV1ResponseAllOfToJSON(value?: EzsignsignatureCreateObjectV1ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mPayload': EzsignsignatureCreateObjectV1ResponseMPayloadToJSON(value.mPayload),
    };
}

