/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FranchisereferalincomeCreateObjectV1ResponseMPayload,
    FranchisereferalincomeCreateObjectV1ResponseMPayloadFromJSON,
    FranchisereferalincomeCreateObjectV1ResponseMPayloadFromJSONTyped,
    FranchisereferalincomeCreateObjectV1ResponseMPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface FranchisereferalincomeCreateObjectV1ResponseAllOf
 */
export interface FranchisereferalincomeCreateObjectV1ResponseAllOf {
    /**
     * 
     * @type {FranchisereferalincomeCreateObjectV1ResponseMPayload}
     * @memberof FranchisereferalincomeCreateObjectV1ResponseAllOf
     */
    mPayload: FranchisereferalincomeCreateObjectV1ResponseMPayload;
}

export function FranchisereferalincomeCreateObjectV1ResponseAllOfFromJSON(json: any): FranchisereferalincomeCreateObjectV1ResponseAllOf {
    return FranchisereferalincomeCreateObjectV1ResponseAllOfFromJSONTyped(json, false);
}

export function FranchisereferalincomeCreateObjectV1ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): FranchisereferalincomeCreateObjectV1ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mPayload': FranchisereferalincomeCreateObjectV1ResponseMPayloadFromJSON(json['mPayload']),
    };
}

export function FranchisereferalincomeCreateObjectV1ResponseAllOfToJSON(value?: FranchisereferalincomeCreateObjectV1ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mPayload': FranchisereferalincomeCreateObjectV1ResponseMPayloadToJSON(value.mPayload),
    };
}

