/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AddressRequest,
    AddressRequestFromJSON,
    AddressRequestFromJSONTyped,
    AddressRequestToJSON,
    ContactRequestCompound,
    ContactRequestCompoundFromJSON,
    ContactRequestCompoundFromJSONTyped,
    ContactRequestCompoundToJSON,
} from './';

/**
 * 
 * @export
 * @interface FranchisereferalincomeRequestCompoundAllOf
 */
export interface FranchisereferalincomeRequestCompoundAllOf {
    /**
     * 
     * @type {AddressRequest}
     * @memberof FranchisereferalincomeRequestCompoundAllOf
     */
    objAddress?: AddressRequest;
    /**
     * 
     * @type {Array<ContactRequestCompound>}
     * @memberof FranchisereferalincomeRequestCompoundAllOf
     */
    a_objContact: Array<ContactRequestCompound>;
}

export function FranchisereferalincomeRequestCompoundAllOfFromJSON(json: any): FranchisereferalincomeRequestCompoundAllOf {
    return FranchisereferalincomeRequestCompoundAllOfFromJSONTyped(json, false);
}

export function FranchisereferalincomeRequestCompoundAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): FranchisereferalincomeRequestCompoundAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'objAddress': !exists(json, 'objAddress') ? undefined : AddressRequestFromJSON(json['objAddress']),
        'a_objContact': ((json['a_objContact'] as Array<any>).map(ContactRequestCompoundFromJSON)),
    };
}

export function FranchisereferalincomeRequestCompoundAllOfToJSON(value?: FranchisereferalincomeRequestCompoundAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'objAddress': AddressRequestToJSON(value.objAddress),
        'a_objContact': ((value.a_objContact as Array<any>).map(ContactRequestCompoundToJSON)),
    };
}

