/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserCreateEzsignuserV1ResponseMPayload,
    UserCreateEzsignuserV1ResponseMPayloadFromJSON,
    UserCreateEzsignuserV1ResponseMPayloadFromJSONTyped,
    UserCreateEzsignuserV1ResponseMPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserCreateEzsignuserV1ResponseAllOf
 */
export interface UserCreateEzsignuserV1ResponseAllOf {
    /**
     * 
     * @type {UserCreateEzsignuserV1ResponseMPayload}
     * @memberof UserCreateEzsignuserV1ResponseAllOf
     */
    mPayload: UserCreateEzsignuserV1ResponseMPayload;
}

export function UserCreateEzsignuserV1ResponseAllOfFromJSON(json: any): UserCreateEzsignuserV1ResponseAllOf {
    return UserCreateEzsignuserV1ResponseAllOfFromJSONTyped(json, false);
}

export function UserCreateEzsignuserV1ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCreateEzsignuserV1ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mPayload': UserCreateEzsignuserV1ResponseMPayloadFromJSON(json['mPayload']),
    };
}

export function UserCreateEzsignuserV1ResponseAllOfToJSON(value?: UserCreateEzsignuserV1ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mPayload': UserCreateEzsignuserV1ResponseMPayloadToJSON(value.mPayload),
    };
}

