/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.39
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AttemptResponse,
    AttemptResponseFromJSON,
    AttemptResponseFromJSONTyped,
    AttemptResponseToJSON,
    CommonWebhook,
    CommonWebhookFromJSON,
    CommonWebhookFromJSONTyped,
    CommonWebhookToJSON,
    UserResponse,
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
    WebhookResponse,
    WebhookResponseFromJSON,
    WebhookResponseFromJSONTyped,
    WebhookResponseToJSON,
    WebhookUserUserCreatedAllOf,
    WebhookUserUserCreatedAllOfFromJSON,
    WebhookUserUserCreatedAllOfFromJSONTyped,
    WebhookUserUserCreatedAllOfToJSON,
} from './';

/**
 * This is the base Webhook object
 * @export
 * @interface WebhookUserUserCreated
 */
export interface WebhookUserUserCreated {
    /**
     * 
     * @type {UserResponse}
     * @memberof WebhookUserUserCreated
     */
    objUser: UserResponse;
    /**
     * 
     * @type {WebhookResponse}
     * @memberof WebhookUserUserCreated
     */
    objWebhook: WebhookResponse;
    /**
     * An array containing details of previous attempts that were made to deliver the message.
     * The array is empty if it's the first attempt.
     * @type {Array<AttemptResponse>}
     * @memberof WebhookUserUserCreated
     */
    a_objAttempt: Array<AttemptResponse>;
}

export function WebhookUserUserCreatedFromJSON(json: any): WebhookUserUserCreated {
    return WebhookUserUserCreatedFromJSONTyped(json, false);
}

export function WebhookUserUserCreatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookUserUserCreated {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'objUser': UserResponseFromJSON(json['objUser']),
        'objWebhook': WebhookResponseFromJSON(json['objWebhook']),
        'a_objAttempt': ((json['a_objAttempt'] as Array<any>).map(AttemptResponseFromJSON)),
    };
}

export function WebhookUserUserCreatedToJSON(value?: WebhookUserUserCreated | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'objUser': UserResponseToJSON(value.objUser),
        'objWebhook': WebhookResponseToJSON(value.objWebhook),
        'a_objAttempt': ((value.a_objAttempt as Array<any>).map(AttemptResponseToJSON)),
    };
}


